### ISSUE TITLE
并没有预约成功提示啊歪

### ISSUE THREAD

**Issue by 2encounter** [ToberHai/library_seat#1]

**Comment by 2encounter** [comment]
即使预约成功也会继续post，严重将会造成系统崩溃，建议根据response.txt内容，判断是否继续post,建议增加计数器，

**Comment by ToberHai** [comment]
等待response返回值的时间太长；系统超过2000条并发会触发DDOS机制，随机丢包，随机丢包后不会给主机返回数据，脚本可能假死。其实根源上解决抢座问题的方法无非就两种，随到随签，扩建自习室
